name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Fetch dependencies
      run: go get
    - name: Build
      run: go build -v ./...
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "ghidraAuth"
        tag: ${{ github.run_number }}
